// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQNYEyypm0CHlMXgcv6QY0ebdGyadKkdQ',
    appId: '1:912550989832:web:f6fa4a44be2c80017741bd',
    messagingSenderId: '912550989832',
    projectId: 'quizowl-1eee8',
    authDomain: 'quizowl-1eee8.firebaseapp.com',
    storageBucket: 'quizowl-1eee8.firebasestorage.app',
    measurementId: 'G-RKVC0JTTRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb5Ubyko2niVYh9rb67lL4wxoKmIXc0lo',
    appId: '1:912550989832:android:97902a2c9bba11207741bd',
    messagingSenderId: '912550989832',
    projectId: 'quizowl-1eee8',
    storageBucket: 'quizowl-1eee8.firebasestorage.app',
  );
}
